### ISSUE TITLE
How to use this project

### ISSUE THREAD

**Issue by KungZell** [bioengstrom/master-thesis#1]
Hello, @isakengstrom 
Thank you very much for making your project public, how do I get the dataset you mentioned and how do I start using the project?
Looking forward to your reply

**Comment by isakengstrom** [comment]
Hi,
Thank you for showing interest in the project, but fortunately, I have not-so-good news.

The dataset is not publicly available, and will probably never be, as it was gathered by the Swedish Defence Research Agency. I mentioned this in the thesis paper, but not in the readme. However, you can read more about the setup if you'd ever want to scrape together something to try to recreate the experiments.
![image](https://user-images.githubusercontent.com/47446279/237056930-7b618da1-f040-4820-b37f-1a237088bf17.png)

It has also been a while since I moved on from the project, getting back into it is very far down on my backlog. I hope the existing code and paper can be of some use, as that's all I can give for now.

/Isak
